server.port=8080

sentry.dsn=http://b39eab2b2c7e94a2dd33bd9480299687@localhost:9000/2
# Add data like request headers and IP for users,
# see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
sentry.send-default-pii=true
# Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
# We recommend adjusting this value in production.
sentry.traces-sample-rate=1.0
sentry.exception-resolver-order=-2147483647

sentry.logging.minimum-event-level=info
sentry.logging.minimum-breadcrumb-level=debug
